name: orcafacil_pro
description: "Aplicativo de Gestão Financeira, Orçamentos e Agendamentos para Profissionais."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  pdf: ^3.10.4
  printing: ^5.11.1
  image_picker: ^1.0.7
  google_sign_in: ^6.2.1
  signature: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo.png